spring:
  application:
    name: TheWalkingDogs
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/the_walking_dogs_app?createDatabaseIfNotExist=true}  #La bd se crea automaticamente si no existe
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

bootstrap:
  number-of-care-givers: 10
